from . import lahendamine
from . import testid
from . import sooritamine
from . import labiviimine
from . import admin
from . import regamine
from . import nimekirjad
from . import hindamine
from . import ettepanek
from . import koolipsyhholoogid
from . import eksamistatistika
from . import tookogumikud
from . import toolaud
from . import tulemused
from . import ylesanded
