
from .ainelabiviija import *
from .ainepedagoog import *
from .aineprofiil import *
from .caetestitud import *
from .isikukaart import *
from .kasutajaajalugu import *
from .kasutajagrupp_oigus import *
from .kasutajagrupp import *
from .kasutajakoht import *
from .kasutajaoigus import *
from .kasutajapiirkond import *
from .kasutaja import *
from .kasutajaroll import *
from .kasutajarollilogi import *
from .kasutajaprotsess import *
from .legacy import *
from .klass import *
from .opilane import *
from .pedagoog import *
from .pedagoogiuuendus import *
from .profiil import *
from .volitus import *
from .makse import *
from .opperyhm import *
from .opperyhmaliige import *

from .kiri import *
from .kirjasaaja import *
from .sooritajakiri import *
from .labiviijakiri import *
from .labiviijaleping import *
from .teavitustellimus import *
from .ettepanek import *
from .tyyptekst import *

from .paring_blokeering import *
from .paring_logi import *
from .paring_tunnistus import *
