#from eistest.model.test import *
from .alatest import *
from .alatestigrupp import *
from .eeltest import *
from .eeltest_komplekt import *
from .erialatest import *
from .eristuskiri import *
from .grupiylesanne import *
from .hindamiskogum import *
from .hindamiskriteerium import *
from .komplekt import *
from .komplektivalik import *
from .kritkirjeldus import *
from .normipunkt import *
from .nptagasiside import *
from .nsgrupp import *
from .salatestiisik import *
from .salatest import *
from .sisestuskogum import *
from .tagasisidefail import *
from .tagasisidevorm import *
from .tagasisidevormidiagramm import *
from .taustakysitlus import *
from .testifailimarkus import *
from .testifail import *
from .testihinne import *
from .testiisik import *
from .testikursus import *
from .testilogi import *
from .testimarkus import *
from .testiosa import *
from .testiplokk import *
from .testitagasiside import *
from .testiylesanne import *
from .test import *
from .testitase import *
from .testsessioon import *
from .t_test import *
from .valitudylesanne import *
from .toofail import *
from .toofailitase import *
from .ylesandegrupp import *
