from .asukohamaarus import *
from .olekuinfo import *
from .aadresskomponent import *
from .aadress import *
from .klaster import *
from .koolioppekava import *
from .kohalogi import *
from .koht import *
from .koolinimi import *
from .oppekeel import *
from .piirkond import *
from .ruum import *
from .ryhm import *
from .sert import *
