#from eistest.model.ylesanne import *
from .abivahend import *
from .hindamisaspekt import *
from .hindamiskysimus import * 
from .hindamismaatriks import *
from .joonistamine import *
from .kasutliik import *
from .kysimus import *
from .kyslisa import *
from .lahendusjuhis import *
from .motlemistasand import *
from .plokimarkus import *
from .punktikirjeldus import *
from .salaylesandeisik import *
from .salaylesanne import *
from .sisuobjekt import *
from .sisuplokk import *
from .testiliik import *
from .tulemusmall import *
from .tulemus import *
from .t_ylesanne import *
from .vahend import *
from .valik import *
from .valikvastus import *
from .valjund import *
from .yhisfail import *
from .ylesandefailimarkus import *
from .ylesandefail import *
from .ylesandeisik import *
from .ylesandelogi import *
from .ylesandeaine import *
from .ylesandeteema import *
from .ylesandeversioon import *
from .ylesanne import *
from .ylopitulemus import *
