# -*- coding: utf-8 -*- 

from lxml import etree
from eis.lib.baseresource import *
_ = i18n._
from eis.lib.block import BlockController

log = logging.getLogger(__name__)

class WmathsettingsController(BaseResourceController):
    """Lahendaja MathType matemaatikaredaktori seadistamine"""

    _permission = 'ylesanded'

    _MODEL = model.Ylesanne
    _EDIT_TEMPLATE = 'ekk/ylesanded/wmathsetting.mako'
    _ITEM_FORM = forms.ekk.ylesanded.WmathsettingForm 

    def _edit(self, item):
        c = self.c
        lahendusjuhis = item.lahendusjuhis
        buf = lahendusjuhis and lahendusjuhis.wmatriba
        c.toolbar = 'general'
        c.detectHand = False
        c.removeLinks = True
        c.tabs = []
        c.icons = []
        c.rows = None
        if not buf:
            # kui seadeid veel ei ole, siis vaikimisi on general toolbar
            # leiame kõik general toolbari vahelehed ja nupud
            for _tb, _tabname, _tabtitle, _icons in self.c.opt_iconsets:
                toolbartb = c.toolbar.startswith('PARCC') and 'PARCC' or c.toolbar
                if _tb == toolbartb:
                    c.tabs.append(_tabname)
                    for iconid, icontitle in _icons:
                        c.icons.append(f'{_tabname}:{iconid}')
        else:
            li = buf.split('|')
            for buf1 in li:
                if buf1 == 'detectHand':
                    c.detectHand = True
                else:
                    # toolbar
                    tree = etree.XML(buf1)
                    c.removeLinks = tree.attrib.get('removeLinks') == 'true'
                    c.toolbar = tree.attrib.get('ref')
                    if c.toolbar:
                        # standardne nupuriba

                        # leiame eemaldatud vahelehed ja nupud
                        remove_tabs = []
                        remove_icons = []
                        for node in tree.iterchildren():
                            if node.tag == 'removeTab':
                                tabname = node.attrib.get('ref')
                                remove_tabs.append(tabname)
                            elif node.tag == 'tab':
                                tabname = node.attrib.get('ref')                                
                                for node2 in node.iterchildren():
                                    if node2.tag == 'removeItem':
                                        _icon = node2.attrib.get('ref')
                                        icon = f'{tabname}:{_icon}'
                                        remove_icons.append(icon)

                        # loetleme kõik vahelehed ja nupud ning jätame eemaldatud välja
                        for _tb, _tabname, _tabtitle, _icons in self.c.opt_iconsets:
                            toolbartb = c.toolbar.startswith('PARCC') and 'PARCC' or c.toolbar
                            if _tb == toolbartb:
                                if _tabname not in remove_tabs:
                                    c.tabs.append(_tabname)
                                    for iconid, icontitle in _icons:
                                        icon = f'{_tabname}:{iconid}'
                                        if icon not in remove_icons:
                                            c.icons.append(icon)
                    else:
                        # isetehtud nupuriba
                        c.toolbar = ''
                        icons = set()
                        for node in tree.iterchildren():
                            #log.debug('ITER %s' % node.tag)
                            if node.tag == 'tab':
                                rows = node.attrib.get('rows')
                                if rows:
                                    c.rows = int(rows)
                                for node2 in node.iterchildren():
                                    #log.debug('   ITER %s' % node2.tag)
                                    if node2.tag == 'item':
                                        _icon = node2.attrib.get('ref')
                                        icons.add(_icon)

                        #log.debug('ICONS=%s' % icons)
                        for _tb, _tabname, _tabtitle, _icons in self.c.opt_iconsets:
                            for iconid, icontitle in _icons:
                                if iconid in icons:
                                    icons.remove(iconid)
                                    icon = f'{_tabname}:{iconid}'
                                    #log.debug(f' ****** APPEND {icon}**')
                                    c.icons.append(icon)

        #log.debug('c.toolbar=%s' % c.toolbar)
        #log.debug('c.tabs=%s' % c.tabs)
        #log.debug('c.icons=%s' % c.icons)
                        
    def _update(self, item):
        lahendusjuhis = item.give_lahendusjuhis()
        data = self.form.data
        removeLinks = data.get('removeLinks')
        detectHand = data.get('detectHand')
        rows = data.get('rows')
        toolbar = data.get('toolbar') 
        tabs = data.get('tab') or []
        icons = data.get('icon') or []

        if toolbar:
            # standardne nupuriba
            buf = f'<toolbar ref="{toolbar}" removeLinks="{removeLinks and "true" or "false"}">'
            for _tb, _tabname, _tabtitle, _icons in self.c.opt_iconsets:
                toolbartb = toolbar.startswith('PARCC') and 'PARCC' or toolbar
                if _tb == toolbartb:
                    if toolbar == 'general' and _tabname not in tabs:
                        buf += f'<removeTab ref="{_tabname}"/>'
                    else:
                        buf1 = ''
                        for iconid, icontitle in _icons:
                            tabicon = f'{_tabname}:{iconid}'
                            if tabicon not in icons:
                                buf1 += f'<removeItem ref="{iconid}"/>'
                        if buf1:
                            buf += f'<tab ref="{_tabname}">{buf1}</tab>'
            buf += '</toolbar>'
        else:
            # isetehtud nupuriba
            buf = f'<toolbar ref="{toolbar}" removeLinks="{removeLinks and "true" or "false"}">'
            buf += '<tab name=""'
            if rows:
                buf += f' rows="{rows}"'
            buf += '>'
            _icons = []
            for icon in icons:
                tabname, _icon = icon.split(':')
                if _icon not in _icons:
                    _icons.append(_icon)
                    buf += f'<item ref="{_icon}"/>'
                    
            buf += '</tab></toolbar>'

        if detectHand:
            buf = 'detectHand|' + buf
        lahendusjuhis.wmatriba = buf
        log.debug('TOOLBAR:%s' % buf)
        self.c.updated = True

    def _after_update(self, id):
        """Mida teha peale õnnestunud salvestamist
        """
        self.success()
        return self.edit()

    def __before__(self):
        """Väärtustame self.c.item ylesandega ning self.c.lang keelega,
        seejuures kontrollime, et self.c.lang oleks selle ülesande tõlkekeel.
        """
        self.c.lang = self.params_lang()
        id = self.request.matchdict.get('id')
        if id:
            self.c.ylesanne = self.c.item = model.Ylesanne.get(id)
            if self.c.lang and (self.c.lang == self.c.item.lang or self.c.lang not in self.c.item.keeled):
                self.c.lang = None
        else:
            self.c.lang = None
        self.c.opt_iconsets = self.wmath_iconsets()            
        super(WmathsettingsController, self).__before__()

    def _perm_params(self):
        return {'obj':self.c.item}
   
    def wmath_iconsets(self):
        iconsets = (
            ('general', 'general', _("Üldine vahekaart"),
             (
                 ('autoDisplayFraction', 'Fraction'),
                 ('autoDisplayBevelledFraction', 'Bevelled fraction'),
                 ('squareRoot', 'Square root'),
                 ('nRoot', 'Root'),
                 ('superscript', 'Superscript'),
                 ('subscript', 'Subscript'),
                 ('parenthesis', 'Parentheses'),
                 ('verticalBar', 'Vertical bars'),
                 ('squareBracket', 'Square brackets'),
                 ('curlyBracket', 'Curly brackets'),
                 ('+', 'Plus sign'),
                 ('&#215;', 'Multiplication sign'),
                 ('-', 'Minus sign'),
                 ('/', 'Forward slash'),
                 ('&#177;', '	Plus-minus sign'),
                 ('&#247;', '	Division sign'),
                 ('&#8805;', 'Greater-than or equal to'),
                 ('&#8804;', 'Less-than or equal to'),
                 ('&#8712;', 'Element of'),
                 ('&#8834;', 'Subset of'),
                 ('&#8746;', 'Union'),
                 ('&#8745;', 'Intersection'),
                 ('&#8709;', 'Empty set'),
                 ('&#8734;', 'Infinity'),
                 ('numberPi', 'Number pi'),
                 ('copy', 'Press Ctrl+C to copy the selection'),
                 ('cut', 'Pess Ctrl+X to cut the selection'),
                 ('paste', 'Press Ctrl+V to paste the content of the clipboard'),
                 ('undo', 'Undo'),
                 ('redo', 'Redo'),
                 ('bold', 'Bold'),
                 ('italic', 'Italic'),
                 ('autoItalic', 'Automatic italic'),
                 ('setColor', 'Color'),
                 ('setUnicode', 'Insert special characters'),
                 ('mtext', 'Regular text'),
                 ('rtl', 'Right to left editing'),
                 ('forceLigature', 'Arabic ligature'),
                 ('setFontFamily', 'Font family'),
                 ('setFontSize', 'Font size'),
                 )
             ),
            ('general', 'symbols', _("Sümbolite vahekaart"),
             (
                 ('negateOperator', 'Negate operator'),
                 ('+', 'Plus sign'),
                 ('-', 'Minus sign'),
                 ('&#177;', 'Plus-minus sign'),
                 ('&#215;', 'Multiplication sign'),
                 ('&#247;', 'Division sign'),
                 ('*', 'Asterisk'),
                 ('&#183;', 'Middle dot'),
                 ('/', 'Forward slash'),
                 ('&#8728;', 'Ring operator'),
                 ('\\', 'Reverse solidus'),
                 ('&#8726;', 'Set minus'),
                 ('&#8723;', 'Minus-or-plus sign'),
                 ('numberPi', 'Number pi'),
                 ('&#8734;', 'Infinity'),
                 ('&#8709;', 'Empty set'),
                 ('&#8706;', 'Partial differential'),
                 ('&#8710;', 'Increment'),
                 ('&#8711;', 'Nabla'),
                 ('&#176;', 'Degree sign'),
                 ('&apos;', 'Apostrophe'),
                 ('aposApos', 'Double apostrophe'),
                 ('triplePrime', 'Triple apostrophe'),
                 ('quadruplePrime', 'Quadruple apostrophe'),
                 ('&#8245;', 'Reversed prime'),
                 ('=', 'Equals sign'),
                 ('&#8764;', 'Tilde operator'),
                 ('&#8771;', 'Asymptotically equal to'),
                 ('&#8801;', 'Identical to'),
                 ('&#8776;', 'Almost equal to'),
                 ('&#8773;', 'Approximately equal to'),
                 ('&#8800;', 'Not equal to'),
                 ('&#8802;', 'Not identical to'),
                 ('&#8769;', 'Not tilde'),
                 ('&#8777;', 'Not almost equal to'),
                 ('&gt;', 'Greater-than sign'),
                 ('&#8805;', 'Greater-than or equal to'),
                 ('&#10878;', 'Greater-than or slanted equal to'),
                 ('&lt;', 'Less-than sign'),
                 ('&#8804;', 'Less-than or equal to'),
                 ('&#10877;', 'Less-than or slanted equal to'),
                 ('&#10887;', 'Less-than and single-line not equal to'),
                 ('&#10888;', 'Greater-than and single-line not equal to'),
                 ('&#8810;', 'Much less-than'),
                 ('&#8811;', 'Much greater-than'),
                 ('&#8733;', 'Proportional to'),
                 ('&#8826;', 'Precedes'),
                 ('&#8827;', 'Succeeds'),
                 ('&#8882;', 'Normal subgroup of'),
                 ('&#8883;', 'Contains as normal subgroup'),
                 ('&#8712;', 'Element of'),
                 ('&#8715;', 'Contains as member'),
                 ('&#8746;', 'Union'),
                 ('&#8745;', 'Intersection'),
                 ('&#8834;', 'Subset of'),
                 ('&#8835;', 'Superset of'),
                 ('&#8713;', 'Not an element of'),
                 ('&#8716;', 'Does not contain as member'),
                 ('&#8838;', 'Subset of or equal to'),
                 ('&#8839;', 'Superset of or equal to'),
                 ('&#8847;', 'Square subset of'),
                 ('&#8848;', 'Square superset of'),
                 ('&#8849;', 'Square subset of or equal to'),
                 ('&#8850;', 'Square superset of or equal to'),
                 ('&#8851;', 'Square cap'),
                 ('&#8852;', 'Square cup'),
                 ('&#8743;', 'Logical and'),
                 ('&#8744;', 'Logical or'),
                 ('&#172;', 'Not sign'),
                 ('&#8704;', 'For all'),
                 ('&#8707;', 'There exists'),
                 ('&#8708;', 'There does not exist'),
                 ('&#8756;', 'Therefore'),
                 ('&#8757;', 'Because'),
                 ('&#8736;', 'Angle'),
                 ('&#8741;', 'Parallel to'),
                 ('&#8869;', 'Perpendicular'),
                 ('&#8742;', 'Not parallel to'),
                 ('&#8737;', 'Measured angle'),
                 ('&#8738;', 'Spherical angle'),
                 ('&#8900;', 'Diamond'),
                 ('&#9633;', 'Square'),
                 ('&#9651;', 'Triangle'),
                 ('&#9675;', 'Circle'),
                 ('&#9645;', ''),
                 ('&#9649;', 'Parallelogram'),
                 ('&#8853;', 'Circled plus'),
                 ('&#8855;', 'Circled times'),
                 ('&#8857;', 'Circled dot'),
                 ('&#8861;', 'Circled dash'),
                 ('&#8859;', 'Circled asterisk'),
                 ('&#10808;', 'Circled division'),
                 ('&#8729;', 'Bullet'),
                 ('euro', 'Euro'),
                 ('yen', 'Yen'),
                 ('pound', 'Pound'),
                 ('cent', 'cent'),
                 ('currency', 'currency'),
                 )
             ),
             ('general', 'arrows', _("Noolte vahekaart"),
              (
                  ('&#8592;', 'Leftwards arrow'),
                  ('&#8594;', 'Rightwards arrow'),
                  ('&#8596;', 'Left right arrow'),
                  ('&#8656;', 'Leftwards double arrow'),
                  ('&#8658;', 'Rightwards double arrow'),
                  ('&#8660;', 'Left right double arrow'),
                  ('&#8612;', 'Leftwards arrow from bar'),
                  ('&#8614;', 'Rightwards arrow from bar'),
                  ('&#8599;', 'North east arrow'),
                  ('&#8600;', 'South east arrow'),
                  ('&#8598;', 'North west arrow'),
                  ('&#8601;', 'South west arrow'),
                  ('&#10529;', ''),
                  ('&#10530;', ''),
                  ('&#8617;', 'Leftwards arrow with hook'),
                  ('&#8618;', 'Rightwards arrow with hook'),
                  ('&#8636;', 'Leftwards harpoon with barb upwards'),
                  ('&#8640;', 'Rightwards harpoon with barb upwards'),
                  ('&#8593;', 'Upwards arrow'),
                  ('&#8595;', 'Downwards arrow'),
                  ('&#8657;', 'Upwards double arrow'),
                  ('&#8659;', 'Downwards double arrow'),
                  ('&#10602;', 'Leftwards harpoon with barb up above long dash'),
                  ('&#10605;', 'Rightwards harpoon with barb down below long dash'),
                  ('&#8651;', 'Leftwards harpoon over rightwards harpoon'),
                  ('&#8652;', 'Rightwards harpoon over leftwards harpoon'),
                  ('&#8637;', 'Leftwards harpoon with barb downwards'),
                  ('&#8641;', 'Rightwards harpoon with barb downwards'),
                  ('&#8646;', 'Leftwards arrow over rightwards arrow'),
                  ('&#8644;', 'Rightwards arrow over leftwards arrow'),
                  ('&#8645;', 'Upwards arrow leftwards of downwards arrow'),
                  ('&#8693;', 'Downwards arrow leftwards of upwards arrow'),
                  ('&#10606;', 'Upwards harpoon with barb left beside downwards harpoon with barb right'),
                  ('&#10607;', 'Downwards harpoon with barb left beside upwards harpoon with barb right'),
                  ('&#10562;', 'Rightwards arrow over short leftwards arrow'),
                  ('&#10564;', 'Short rightwards arrow over leftwards arrow'),
                  ('&#8597;', 'Up down arrow'),
                  ('&#8661;', 'Up down double arrow'),
                  ('&#8629;', 'Downwards arrow with corner leftwards'),
                  ('&#8942;', 'Vertical ellipsis'),
                  ('&#8230;', 'Horizontal ellipsis'),
                  ('&#8943;', 'Midline horizontal ellipsis'),
                  ('&#8944;', 'Up right diagonal ellipsis'),
                  ('&#8945;', 'Down right diagonal ellipsis'),
                  ('&#8208;', 'Short dash'),
                  ('normalDash', 'Dash'),
                  ('&#8212;', 'Long dash'),
                  ('rightArrowWithOverScript', 'Right arrow with over script'),
                  ('rightArrowWithUnderScript', 'Right arrow with under script'),
                  ('rightArrowWithUnderAndOverScript', 'Right arrow with under and over script'),
                  ('leftArrowWithOverScript', 'Left arrow with over script'),
                  ('leftArrowWithUnderScript', 'Left arrow with under script'),
                  ('leftArrowWithUnderAndOverScript', 'Left arrow with under and over script'),
                  ('rightLeftArrowWithOverScript', 'Right left arrow with over script'),
                  ('rightLeftArrowWithUnderScript', 'Right left arrow with under script'),
                  ('rightLeftArrowWithUnderAndOverScript', 'Right left arrow with under and over script'),
                  ('leftArrowOverRightArrowWithOverScript', 'Left arrow with over right arrow with over script'),
                  ('leftArrowOverRightArrowWithUnderScript', 'Left arrow over right arrow with under script'),
                  ('leftArrowOverRightArrowWithUnderAndOverScript', 'Left arrow over right arrow with under and over script'),
                  ('rightArrowOverLeftArrowWithOverScript', 'Right arrow over left arrow with over script'),
                  ('rightArrowOverLeftArrowWithUnderScript', 'Right arrow over left arrow with under script'),
                  ('rightArrowOverLeftArrowWithUnderAndOverScript', 'Right arrow over left arrow with under and over script'),
                  ('leftHarpoonOverRightHarpoonWithOverScript', 'Left harpoon over right harpoon with over script'),
                  ('leftHarpoonOverRightHarpoonWithUnderScript', 'Left harpoon over right harpoon with under script'),
                  ('leftHarpoonOverRightHarpoonWithUnderAndOverScript', 'Left harpoon over right harpoon with under and over script'),
                  ('rightHarpoonOverLeftHarpoonWithOverScript', 'Right harpoon over left harpoon with over script'),
                  ('rightHarpoonOverLeftHarpoonWithUnderScript', 'Right harpoon over left harpoon with under script'),
                  ('rightHarpoonOverLeftHarpoonWithUnderAndOverScript', 'Right harpoon over left harpoon with under and over script'),
                  ('rightArrowOverShortLeftWithOverScript', 'Rightwards arrow over short leftwards arrow with over script'),
                  ('rightArrowOverShortLeftWithUnderScript', 'Rightwards arrow over short leftwards arrow with under script'),
                  ('rightArrowOverShortLeftWithUnderAndOverScript', 'Rightwards arrow over short leftwards arrow with under and over script'),
                  ('shortRightArrowOverLeftWithOverScript', 'Short rightwards arrow over leftwards arrow with over script'),
                  ('shortRightArrowOverLeftWithUnderScript', 'Short rightwards arrow over leftwards arrow with under script'),
                  ('shortRightArrowOverLeftWithUnderAndOverScript', 'Short rightwards arrow over leftwards arrow with under and over script'),
                  ('vectorAccent', 'Vector accent'),
                  ('rightArrowAccent', 'Arrow accent'),
                  ('rightLeftArrowAccent', 'Left right arrow accent'),
                  ('barAccent', 'Bar accent'),
                  )
              ),
            ('general', 'greek', _("Tähtede ja numbrite vahekaart"),
             (
                  ('&#945;', 'Alpha'),
                  ('&#946;', 'Beta'),
                  ('&#947;', 'Gamma'),
                  ('&#948;', 'Delta'),
                  ('&#949;', 'Epsilon'),
                  ('&#950;', 'Zeta'),
                  ('&#951;', 'Eta'),
                  ('&#952;', 'Theta'),
                  ('&#977;', 'Theta'),
                  ('&#953;', 'Iota'),
                  ('&#954;', 'Kappa'),
                  ('&#955;', 'Lambda'),
                  ('&#956;', 'Mu'),
                  ('&#957;', 'Nu'),
                  ('&#958;', 'Xi'),
                  ('&#959;', 'Omicron'),
                  ('&#960;', 'Pi'),
                  ('&#982;', 'Pi'),
                  ('&#961;', 'Rho'),
                  ('&#962;', 'Final sigma'),
                  ('&#963;', 'Sigma'),
                  ('&#964;', 'Tau'),
                  ('&#965;', 'Upsilon'),
                  ('&#966;', 'Phi'),
                  ('&#981;', 'Phi'),
                  ('&#967;', 'Chi'),
                  ('&#968;', 'Psi'),
                  ('&#969;', 'Omega'),
                  ('&#913;', 'Capital alpha'),
                  ('&#914;', 'Capital beta'),
                  ('&#915;', 'Capital gamma'),
                  ('&#916;', 'Capital delta'),
                  ('&#917;', 'Capital epsilon'),
                  ('&#918;', 'Capital zeta'),
                  ('&#919;', 'Capital eta'),
                  ('&#920;', 'Capital theta'),
                  ('&#921;', 'Capital iota'),
                  ('&#922;', 'Capital kappa'),
                  ('&#923;', 'Capital lambda'),
                  ('&#924;', 'Capital mu'),
                  ('&#925;', 'Capital nu'),
                  ('&#926;', 'Capital xi'),
                  ('&#927;', 'Capital omicron'),
                  ('&#928;', 'Capital pi'),
                  ('&#929;', 'Capital rho'),
                  ('&#931;', 'Capital sigma'),
                  ('&#932;', 'Capital tau'),
                  ('&#933;', 'Capital upsilon'),
                  ('&#934;', 'Capital phi'),
                  ('&#935;', 'Capital chi'),
                  ('&#936;', 'Capital psi'),
                  ('&#937;', 'Capital omega'),
                  ('naturals', 'Natural numbers (double-struck capital n)'),
                  ('rationals', 'Rational numbers (double-struck capital q)'),
                  ('reals', 'Real numbers (double-struck capital r)'),
                  ('integers', 'Integer numbers (double-struck capital z)'),
                  ('complexes', 'Complex numbers (double-struck capital c)'),
                  ('primes', 'Prime numbers (double-struck capital p)'),
                  ('doubleStruckCapitalA', 'Double struck capital a'),
                  ('doubleStruckCapitalB', 'Double struck capital b'),
                  ('complexes', 'Complex numbers (double-struck capital c)'),
                  ('doubleStruckCapitalD', 'Double struck capital d'),
                  ('doubleStruckCapitalE', 'Double struck capital e'),
                  ('doubleStruckCapitalF', 'Double struck capital f'),
                  ('doubleStruckCapitalG', 'Double struck capital g'),
                  ('doubleStruckCapitalH', 'Double struck capital h'),
                  ('imaginaries', 'Imaginary numbers (double-struck capital i)'),
                  ('doubleStruckCapitalJ', 'Double struck capital j'),
                  ('doubleStruckCapitalK', 'Double struck capital k'),
                  ('doubleStruckCapitalL', 'Double struck capital l'),
                  ('doubleStruckCapitalM', 'Double struck capital m'),
                  ('naturals', 'Natural numbers (double-struck capital n)'),
                  ('doubleStruckCapitalO', 'Double struck capital o'),
                  ('primes', 'Prime numbers (double-struck capital p)'),
                  ('rationals', 'Rational numbers (double-struck capital q)'),
                  ('reals', 'Real numbers (double-struck capital r)'),
                  ('doubleStruckCapitalS', 'Double struck capital s'),
                  ('doubleStruckCapitalT', 'Double struck capital t'),
                  ('doubleStruckCapitalU', 'Double struck capital u'),
                  ('doubleStruckCapitalV', 'Double struck capital v'),
                  ('doubleStruckCapitalW', 'Double struck capital w'),
                  ('doubleStruckCapitalX', 'Double struck capital x'),
                  ('doubleStruckCapitalY', 'Double struck capital y'),
                  ('integers', 'Integer numbers (double-struck capital z)'),
                  ('doubleStruckA', 'Double struck a'),
                  ('doubleStruckB', 'Double struck b'),
                  ('doubleStruckC', 'Double struck c'),
                  ('doubleStruckD', 'Double struck d'),
                  ('doubleStruckE', 'Double struck e'),
                  ('doubleStruckF', 'Double struck f'),
                  ('doubleStruckG', 'Double struck g'),
                  ('doubleStruckH', 'Double struck h'),
                  ('doubleStruckI', 'Double struck i'),
                  ('doubleStruckJ', 'Double struck j'),
                  ('doubleStruckK', 'Double struck k'),
                  ('doubleStruckL', 'Double struck l'),
                  ('doubleStruckM', 'Double struck m'),
                  ('doubleStruckN', 'Double struck n'),
                  ('doubleStruckO', 'Double struck o'),
                  ('doubleStruckP', 'Double struck p'),
                  ('doubleStruckQ', 'Double struck q'),
                  ('doubleStruckR', 'Double struck r'),
                  ('doubleStruckS', 'Double struck s'),
                  ('doubleStruckT', 'Double struck t'),
                  ('doubleStruckU', 'Double struck u'),
                  ('doubleStruckV', 'Double struck v'),
                  ('doubleStruckW', 'Double struck w'),
                  ('doubleStruckX', 'Double struck x'),
                  ('doubleStruckY', 'Double struck y'),
                  ('doubleStruckZ', 'Double struck z'),
                  ('frakturCapitalA', 'Fraktur capital a'),
                  ('frakturCapitalB', 'Fraktur capital b'),
                  ('frakturCapitalC', 'Fraktur capital c'),
                  ('frakturCapitalA', 'Fraktur capital a'),
                  ('frakturCapitalB', 'Fraktur capital b'),
                  ('frakturCapitalC', 'Fraktur capital c'),
                  ('frakturCapitalD', 'Fraktur capital d'),
                  ('frakturCapitalE', 'Fraktur capital e'),
                  ('frakturCapitalF', 'Fraktur capital f'),
                  ('frakturCapitalG', 'Fraktur capital g'),
                  ('frakturCapitalH', 'Fraktur capital h'),
                  ('frakturCapitalI', 'Fraktur capital i'),
                  ('frakturCapitalJ', 'Fraktur capital j'),
                  ('frakturCapitalK', 'Fraktur capital k'),
                  ('frakturCapitalL', 'Fraktur capital l'),
                  ('frakturCapitalM', 'Fraktur capital m'),
                  ('frakturCapitalN', 'Fraktur capital n'),
                  ('frakturCapitalO', 'Fraktur capital o'),
                  ('frakturCapitalP', 'Fraktur capital p'),
                  ('frakturCapitalQ', 'Fraktur capital q'),
                  ('frakturCapitalR', 'Fraktur capital r'),
                  ('frakturCapitalS', 'Fraktur capital s'),
                  ('frakturCapitalT', 'Fraktur capital t'),
                  ('frakturCapitalU', 'Fraktur capital u'),
                  ('frakturCapitalV', 'Fraktur capital v'),
                  ('frakturCapitalW', 'Fraktur capital w'),
                  ('frakturCapitalX', 'Fraktur capital x'),
                  ('frakturCapitalY', 'Fraktur capital y'),
                  ('frakturCapitalZ', 'Fraktur capital z'),
                  ('frakturA', 'Fraktur a'),
                  ('frakturB', 'Fraktur b'),
                  ('frakturC', 'Fraktur c'),
                  ('frakturD', 'Fraktur d'),
                  ('frakturE', 'Fraktur e'),
                  ('frakturF', 'Fraktur f'),
                  ('frakturG', 'Fraktur g'),
                  ('frakturH', 'Fraktur h'),
                  ('frakturI', 'Fraktur i'),
                  ('frakturJ', 'Fraktur j'),
                  ('frakturK', 'Fraktur k'),
                  ('frakturL', 'Fraktur l'),
                  ('frakturM', 'Fraktur m'),
                  ('frakturN', 'Fraktur n'),
                  ('frakturO', 'Fraktur o'),
                  ('frakturP', 'Fraktur p'),
                  ('frakturQ', 'Fraktur q'),
                  ('frakturR', 'Fraktur r'),
                  ('frakturS', 'Fraktur s'),
                  ('frakturT', 'Fraktur t'),
                  ('frakturU', 'Fraktur u'),
                  ('frakturV', 'Fraktur v'),
                  ('frakturW', 'Fraktur w'),
                  ('frakturX', 'Fraktur x'),
                  ('frakturY', 'Fraktur y'),
                  ('frakturZ', 'Fraktur z'),
                  ('scriptCapitalA', 'Script capital a'),
                  ('scriptCapitalB', 'Script capital b'),
                  ('scriptCapitalC', 'Script capital c'),
                  ('scriptCapitalA', 'Script capital a'),
                  ('scriptCapitalB', 'Script capital b'),
                  ('scriptCapitalC', 'Script capital c'),
                  ('scriptCapitalD', 'Script capital d'),
                  ('scriptCapitalE', 'Script capital e'),
                  ('scriptCapitalF', 'Script capital f'),
                  ('scriptCapitalG', 'Script capital g'),
                  ('scriptCapitalH', 'Script capital h'),
                  ('scriptCapitalI', 'Script capital i'),
                  ('scriptCapitalJ', 'Script capital j'),
                  ('scriptCapitalK', 'Script capital k'),
                  ('scriptCapitalL', 'Script capital l'),
                  ('scriptCapitalM', 'Script capital m'),
                  ('scriptCapitalN', 'Script capital n'),
                  ('scriptCapitalO', 'Script capital o'),
                  ('scriptCapitalP', 'Script capital p'),
                  ('scriptCapitalQ', 'Script capital q'),
                  ('scriptCapitalR', 'Script capital r'),
                  ('scriptCapitalS', 'Script capital s'),
                  ('scriptCapitalT', 'Script capital t'),
                  ('scriptCapitalU', 'Script capital u'),
                  ('scriptCapitalV', 'Script capital v'),
                  ('scriptCapitalW', 'Script capital w'),
                  ('scriptCapitalX', 'Script capital x'),
                  ('scriptCapitalY', 'Script capital y'),
                  ('scriptCapitalZ', 'Script capital z'),
                  ('scriptA', 'Script a'),
                  ('scriptB', 'Script b'),
                  ('scriptC', 'Script c'),
                  ('scriptD', 'Script d'),
                  ('scriptE', 'Script e'),
                  ('scriptF', 'Script f'),
                  ('scriptG', 'Script g'),
                  ('scriptH', 'Script h'),
                  ('scriptI', 'Script i'),
                  ('scriptJ', 'Script j'),
                  ('scriptK', 'Script k'),
                  ('scriptL', 'Script l'),
                  ('scriptM', 'Script m'),
                  ('scriptN', 'Script n'),
                  ('scriptO', 'Script o'),
                  ('scriptP', 'Script p'),
                  ('scriptQ', 'Script q'),
                  ('scriptR', 'Script r'),
                  ('scriptS', 'Script s'),
                  ('scriptT', 'Script t'),
                  ('scriptU', 'Script u'),
                  ('scriptV', 'Script v'),
                  ('scriptW', 'Script w'),
                  ('scriptX', 'Script x'),
                  ('scriptY', 'Script y'),
                  ('scriptZ', 'Script z'),
                  ('&#8465;', 'Imaginary part (black-letter capital i)'),
                  ('&#8476;', 'Real part (black-letter capital r)'),
                  ('ell', 'Ell'),
                  ('&#8501;', 'Alef'),
                  ('&#8472;', 'Script capital p'),
                  ('&#8497;', 'Script capital f'),
                  ('&#8466;', 'Script capital l'),
                  ('zTransform', 'Z transform'),
                  ('arabicIndicNumbers', 'Arabic-Indic numerals'),
                  ('easternArabicIndicNumbers', 'Eastern Arabic-Indic numerals'),
                  ('hydrogen', 'Hydrogen'),
                  ('nitrogen', 'Nitrogen'),
                  ('fluorine', 'Fluorine'),
                  ('carbon', 'Carbon'),
                  ('oxygen', 'Oxygen'),
                  ('sulfur', 'Sulfur'),
                  ('hydrogen', 'Hydrogen'),
                  ('helium', 'Helium'),
                  ('lithium', 'Lithium'),
                  ('beryllium', 'Beryllium'),
                  ('boron', 'Boron'),
                  ('carbon', 'Carbon'),
                  ('nitrogen', 'Nitrogen'),
                  ('oxygen', 'Oxygen'),
                  ('fluorine', 'Fluorine'),
                  ('neon', 'Neon'),
                  ('sodium', 'Sodium'),
                  ('magnesium', 'Magnesium'),
                  ('aluminium', 'Aluminium'),
                  ('silicon', 'Silicon'),
                  ('phosphorus', 'Phosphorus'),
                  ('sulfur', 'Sulfur'),
                  ('chlorine', 'Chlorine'),
                  ('argon', 'Argon'),
                  ('potassium', 'Potassium'),
                  ('calcium', 'Calcium'),
                  ('scandium', 'Scandium'),
                  ('titanium', 'Titanium'),
                  ('vanadium', 'Vanadium'),
                  ('chromium', 'Chromium'),
                  ('manganese', 'Manganese'),
                  ('iron', 'Iron'),
                  ('cobalt', 'Cobalt'),
                  ('nickel', 'Nickel'),
                  ('copper', 'Copper'),
                  ('zinc', 'Zinc'),
                  ('gallium', 'Gallium'),
                  ('germanium', 'Germanium'),
                  ('arsenic', 'Arsenic'),
                  ('selenium', 'Selenium'),
                  ('bromine', 'Bromine'),
                  ('krypton', 'Krypton'),
                  ('rubidium', 'Rubidium'),
                  ('strontium', 'Strontium'),
                  ('yttrium', 'Yttrium'),
                  ('zirconium', 'Zirconium'),
                  ('niobium', 'Niobium'),
                  ('molybdenum', 'Molybdenum'),
                  ('technetium', 'Technetium'),
                  ('ruthenium', 'Ruthenium'),
                  ('rhodium', 'Rhodium'),
                  ('palladium', 'Palladium'),
                  ('silver', 'Silver'),
                  ('cadmium', 'Cadmium'),
                  ('indium', 'Indium'),
                  ('tin', 'Tin'),
                  ('antimony', 'Antimony'),
                  ('tellurium', 'Tellurium'),
                  ('iodine', 'Iodine'),
                  ('xenon', 'Xenon'),
                  ('caesium', 'Caesium'),
                  ('barium', 'Barium'),
                  ('hafnium', 'Hafnium'),
                  ('tantalum', 'Tantalum'),
                  ('tungsten', 'Tungsten'),
                  ('rhenium', 'Rhenium'),
                  ('osmium', 'Osmium'),
                  ('iridium', 'Iridium'),
                  ('platinum', 'Platinum'),
                  ('gold', 'Gold'),
                  ('mercury', 'Mercury'),
                  ('thallium', 'Thallium'),
                  ('lead', 'Lead'),
                  ('bismuth', 'Bismuth'),
                  ('polonium', 'Polonium'),
                  ('astatine', 'Astatine'),
                  ('radon', 'Radon'),
                  ('francium', 'Francium'),
                  ('radium', 'Radium'),
                  ('rutherfordium', 'Rutherfordium'),
                  ('dubnium', 'Dubnium'),
                  ('seaborgium', 'Seaborgium'),
                  ('bohrium', 'Bohrium'),
                  ('hassium', 'Hassium'),
                  ('meitnerium', 'Meitnerium'),
                  ('damstadtium', 'Darmstadtium'),
                  ('roentgenium', 'Roentgenium'),
                  ('copernicium', 'Copernicium'),
                  ('nihonium', 'Nihonium'),
                  ('flerovium', 'Flerovium'),
                  ('moscovium', 'Moscovium'),
                  ('livermorium', 'Livermorium'),
                  ('tennessine', 'Tennessine'),
                  ('oganesson', 'Oganesson'),
                  ('lanthanum', 'Lanthanum'),
                  ('cerium', 'Cerium'),
                  ('praseodymium', 'Praseodymium'),
                  ('neodymium', 'Neodymium'),
                  ('promethium', 'Promethium'),
                  ('samarium', 'Samarium'),
                  ('europium', 'Europium'),
                  ('gadolinium', 'Gadolinium'),
                  ('terbium', 'Terbium'),
                  ('dysprosium', 'Dysprosium'),
                  ('holmium', 'Holmium'),
                  ('erbium', 'Erbium'),
                  ('thulium', 'Thulium'),
                  ('ytterbium', 'Ytterbium'),
                  ('lutetium', 'Lutetium'),
                  ('actinium', 'Actinium'),
                  ('thorium', 'Thorium'),
                  ('protactinium', 'Protactinium'),
                  ('uranium', 'Uranium'),
                  ('neptunium', 'Neptunium'),
                  ('plutonium', 'Plutonium'),
                  ('americium', 'Americium'),
                  ('curium', 'Curium'),
                  ('berkelium', 'Barkelium'),
                  ('californium', 'Californium'),
                  ('einsteinium', 'Einsteinium'),
                  ('fermium', 'Fermium'),
                  ('mendelevium', 'Mendelevium'),
                  ('nobelium', 'Nobelium'),
                  ('lawrencium', 'Lawrencium'),
                  ),
              ),
            ('general', 'matrices', _("Maatriksite ja elementide vahekaart"),
             (
                 ('table', 'Table'),
                 ('squareTable', 'Matrix with square brackets'),
                 ('verticalLineTable', 'Matrix with vertical bars'),
                 ('parenthesisTable', 'Matrix with parenthesis'),
                 ('separatedParenthesisTable', 'separatedParenthesisTable'),
                 ('column', '3 rows column'),
                 ('row', '3 column row'),
                 ('squareColumn', '2 rows column with square brackets'),
                 ('squareRow', '2 columns row with square brackets'),
                 ('parenthesisColumn', '2 rows column with parenthesis'),
                 ('parenthesisRow', '2 columns row with parenthesis'),
                 ('lCurlyColumn', '2 rows column with left curly brackets'),
                 ('rCurlyColumn', '2 rows column with right curly brackets'),
                 ('piecewiseFunction', 'Piecewise function'),
                 ('equationAlign', 'Aligned equations'),
                 ('&#8942;', 'Vertical ellipsis'),
                 ('&#8943;', 'Midline horizontal ellipsis'),
                 ('&#8944;', 'Up right diagonal ellipsis'),
                 ('&#8945;', 'Down right diagonal ellipsis'),
                 ('3RowsStackWithLineAndPlusSign', '3 rows stack with line and plus sign'),
                 ('longDivision', 'Long division (used in the United States, Great Britain, and elsewhere)'),
                 ('3RowsStackWithLine', '3 rows stack with line'),
                 ('3RowsStackWithLineAndMinusSign', '3 rows stack with line and minus sign'),
                 ('3RowsStackWithLineAndMultiplicationSign', '3 rows stack with line and multiplication sign'),
                 ('longDivisionShortStackedRightRight', 'Long division (used in Spain, Brazil and elsewhere)'),
                 ('longDivisionShortStackedRightRightWithRemainder', 'Long division with remainder (used in Spain, Brazil and elsewhere)'),
                 ('longDivisionWithRemainder', 'Long division with remainder (used in the United States, Great Britain, and elsewhere)'),
                 ),
             ),
             ('general', 'scriptsAndLayout', _("Kirjade ja paigutuse vahekaart"),
              (
                  ('fraction', 'Big fraction'),
                  ('bevelledFraction', 'Bevelled big fraction'),
                  ('smallFraction', 'Small fraction'),
                  ('smallBevelledFraction', 'Bevelled small fraction'),
                  ('squareRoot', 'Square root'),
                  ('nRoot', 'Root'),
                  ('superscript', 'Superscript'),
                  ('subsuperscript', 'Superscript and subscript'),
                  ('subscript', 'Subscript'),
                  ('leftSuperscript', 'Left superscript'),
                  ('leftSubscriptAndSuperscript', 'Left subscript and superscript'),
                  ('leftSubscript', 'Left subscript'),
                  ('over', 'Element over'),
                  ('underover', 'Elements under and over'),
                  ('under', 'Element under'),
                  ('underScriptWithBrace', 'Under script with brace'),
                  ('overScriptWithBrace', 'Over script with brace'),
                  ('bigOpUnderover', 'Big operator with under and over scripts'),
                  ('bigOpUnder', 'Big operator with under script'),
                  ('bigOpSubsuperscript', 'Big operator with subscript and superscript'),
                  ('bigOpSubscript', 'Big operator with subscript'),
                  ('digitSpace', 'Digit space'),
                  ('backSpace', 'Back space'),
                  ('thinnerSpace', 'Thinner space'),
                  ('thinSpace', 'Thin space'),
                  )
              ),
             ('general', 'bracketsAndAccents', _("Dekoratsioonide vahekaart"),
              (
                  ('parenthesis', 'Parentheses'),
                  ('squareBracket', 'Square brackets'),
                  ('verticalBar', 'Vertical bars'),
                  ('doubleVerticalBar', 'Double vertical bars'),
                  ('angleBrackets', 'Angle brackets'),
                  ('curlyBracket', 'Curly brackets'),
                  ('openParenthesis', 'Open stretchy parenthesis'),
                  ('closeParenthesis', 'Close stretchy parenthesis'),
                  ('openSquareBracket', 'Open stretchy square bracket'),
                  ('closeSquareBracket', 'Close stretchy square bracket'),
                  ('openVerticalBar', 'Open stretchy vertical bar'),
                  ('closeVerticalBar', 'Close stretchy vertical bar'),
                  ('openDoubleVerticalBar', 'Open stretchy double vertical bar'),
                  ('closeDoubleVerticalBar', 'Close stretchy double vertical bar'),
                  ('openAngleBracket', 'openAngleBracket'),
                  ('closeAngleBracket', 'closeAngleBracket'),
                  ('openCurlyBracket', 'Open stretchy curly bracket'),
                  ('closeCurlyBracket', 'Close stretchy curly bracket'),
                  ('floor', 'Floor'),
                  ('ceiling', 'Ceiling'),
                  ('angleBracketsWithBar', 'Angle brackets with bar'),
                  ('upCurlyBracket', 'Top curly bracket'),
                  ('downCurlyBracket', 'Bottom curly bracket'),
                  ('upParenthesis', 'Top parenthesis'),
                  ('downParenthesis', 'Bottom parenthesis'),
                  ('vectorAccent', 'Vector accent'),
                  ('rightArrowAccent', 'Arrow accent'),
                  ('rightLeftArrowAccent', 'Left right arrow accent'),
                  ('barAccent', 'Bar accent'),
                  ('hatAccent', 'Hat accent'),
                  ('tilde', 'Tilde'),
                  ('diaeresis', 'Diaeresis'),
                  ('dotAccent', 'Dot accent'),
                  ('encloseTop', 'Enclose top'),
                  ('encloseBottom', 'Enclose bottom'),
                  ('encloseLeft', 'Enclose left'),
                  ('encloseRight', 'Enclose right'),
                  ('encloseBox', 'Enclose box'),
                  ('encloseCircle', 'Enclose circle'),
                  ('encloseActuarial', 'Enclose actuarial'),
                  ('encloseRoundedBox', 'Enclose rounded box'),
                  ('upDiagonalStrike', 'Up diagonal strike'),
                  ('downDiagonalStrike', 'Down diagonal strike'),
                  ('horizontalStrike', 'Horizontal strike'),
                  ('upAndDownDiagonalStrike', 'Up and down diagonal strike'),
                  ('verticalStrike', 'Vertical strike'),
                  ('horizontalAndVerticalStrike', 'Horizontal and vertical strikes'),
                  ('encloseLongDivision', 'Long division'),
                  )
              ),
             ('general', 'bigOps', _("Suurte tehtemärkide vahekaart"),
              (
                  ('sumUnderover', 'Summation with under and over scripts'),
                  ('sumUnder', 'Summation with under scripts'),
                  ('sumSubsuperscript', 'Summation with subscript and superscript'),
                  ('sumSubscript', 'Summation with subscript'),
                  ('productUnderover', 'Product with under and over scripts'),
                  ('productUnder', 'Product with under scripts'),
                  ('productSubsuperscript', 'Product with subscript and superscript'),
                  ('productSubscript', 'Product with subscript'),
                  ('bigOpUnderover', 'Big operator with under and over scripts'),
                  ('bigOpUnder', 'Big operator with under script'),
                  ('bigOpSubsuperscript', 'Big operator with subscript and superscript'),
                  ('bigOpSubscript', 'Big operator with subscript'),
                  ('bigCap', 'Big intersection'),
                  ('bigCup', 'Big union'),
                  ('bigSqCap', 'Big square cap'),
                  ('bigSqCup', 'Big square cup'),
                  ('bigProd', 'Product'),
                  ('bigCoProd', 'Coproduct'),
                  ('bigSum', 'Sum'),
                  )
              ),
             ('general', 'calculus', _("Arvutuse vahekaart"),
              (
                  ('integralSubsuperscript', 'Definite integral'),
                  ('integralSubscript', 'Integral with subscript'),
                  ('integralSubsuperscriptD', 'Definite integral with differential'),
                  ('integralSubscriptD', 'Integral with subscript and differential'),
                  ('differentialD', 'Differential'),
                  ('&#8706;', 'Partial differential'),
                  ('fracDiff', 'Derivative'),
                  ('fracPartial', 'Partial derivative'),
                  ('limitToInfinity', 'Limit to infinity'),
                  ('limitUnder', 'Limit with under script'),
                  ('curl', 'Curl'),
                  ('divergence', 'Divergence'),
                  ('gradient', 'Gradient'),
                  ('laplacian', 'Laplacian'),
                  ('&#8747;', 'Integral'),
                  ('&#8750;', 'Contour integral'),
                  ('&#8748;', 'Double integral'),
                  ('&#8751;', 'Surface integral'),
                  ('&#8749;', 'Triple integral'),
                  ('&#8752;', 'Volume integral'),
                  ('sinus', 'Sine'),
                  ('cosinus', 'Cosine'),
                  ('tangent', 'Tangent'),
                  ('log', 'Logarithm'),
                  ('nlog', 'Logarithm to base n'),
                  ('naturalLog', 'Natural logarithm'),
                  ('cosecant', 'Cosecant'),
                  ('secant', 'Secant'),
                  ('cotangent', 'Cotangent'),
                  ('arcsinus', 'Arcsine'),
                  ('arccosinus', 'Arccosine'),
                  ('arctangent', 'Arctangent'),
                  ('andOperator', 'andOperator'),
                  ('orOperator', 'orOperator'),
                  ('xorOperator', 'xorOperator'),
                  ('notOperator', 'notOperator'),
                  ('sen', 'sen'),
                  )
              ),
             ('quizzes', 'quizzes', 'Nuputamine',
              (
                  ('numberE', 'Number e'),
                  ('imaginaryI', 'Imaginary number i'),
                  ('imaginaryJ', 'Imaginary number j'),
                  ('dotAsTimes', 'Dot as multiplication'),
                  ('&#8240;', 'Per mille'),
                  ('parenthesisTable', 'Matrix with parenthesis'),
                  ('repeatingDecimalOverBar', 'Repeating decimals'),
                  ('repeatingDecimalUnderBar', 'Repeating decimals'),
                  ('repeatingDecimalOverParentheses', 'Repeating decimals'),
                  ('binomialCoefficient', 'Binomial coefficient'),
                  ('asin', 'Arcsine'),
                  ('acos', 'Arccosine'),
                  ('atan', 'Arctangent'),
                  ('exp', 'Exponential'),
                  ('round', 'Round'),
                  )
              ),
             ('chemistry', 'chemistry', 'Keemia',
              (
                  ('hydrogen', 'Hydrogen'),
                  ('nitrogen', 'Nitrogen'),
                  ('fluorine', 'Fluorine'),
                  ('carbon', 'Carbon'),
                  ('oxygen', 'Oxygen'),
                  ('sulfur', 'Sulfur'),
                  ('hydrogen', 'Hydrogen'),
                  ('helium', 'Helium'),
                  ('lithium', 'Lithium'),
                  ('beryllium', 'Beryllium'),
                  ('boron', 'Boron'),
                  ('carbon', 'Carbon'),
                  ('nitrogen', 'Nitrogen'),
                  ('oxygen', 'Oxygen'),
                  ('fluorine', 'Fluorine'),
                  ('neon', 'Neon'),
                  ('sodium', 'Sodium'),
                  ('magnesium', 'Magnesium'),
                  ('aluminium', 'Aluminium'),
                  ('silicon', 'Silicon'),
                  ('phosphorus', 'Phosphorus'),
                  ('sulfur', 'Sulfur'),
                  ('chlorine', 'Chlorine'),
                  ('argon', 'Argon'),
                  ('potassium', 'Potassium'),
                  ('calcium', 'Calcium'),
                  ('scandium', 'Scandium'),
                  ('titanium', 'Titanium'),
                  ('vanadium', 'Vanadium'),
                  ('chromium', 'Chromium'),
                  ('manganese', 'Manganese'),
                  ('iron', 'Iron'),
                  ('cobalt', 'Cobalt'),
                  ('nickel', 'Nickel'),
                  ('copper', 'Copper'),
                  ('zinc', 'Zinc'),
                  ('gallium', 'Gallium'),
                  ('germanium', 'Germanium'),
                  ('arsenic', 'Arsenic'),
                  ('selenium', 'Selenium'),
                  ('bromine', 'Bromine'),
                  ('krypton', 'Krypton'),
                  ('rubidium', 'Rubidium'),
                  ('strontium', 'Strontium'),
                  ('yttrium', 'Yttrium'),
                  ('zirconium', 'Zirconium'),
                  ('niobium', 'Niobium'),
                  ('molybdenum', 'Molybdenum'),
                  ('technetium', 'Technetium'),
                  ('ruthenium', 'Ruthenium'),
                  ('rhodium', 'Rhodium'),
                  ('palladium', 'Palladium'),
                  ('silver', 'Silver'),
                  ('cadmium', 'Cadmium'),
                  ('indium', 'Indium'),
                  ('tin', 'Tin'),
                  ('antimony', 'Antimony'),
                  ('tellurium', 'Tellurium'),
                  ('iodine', 'Iodine'),
                  ('xenon', 'Xenon'),
                  ('caesium', 'Caesium'),
                  ('barium', 'Barium'),
                  ('hafnium', 'Hafnium'),
                  ('tantalum', 'Tantalum'),
                  ('tungsten', 'Tungsten'),
                  ('rhenium', 'Rhenium'),
                  ('osmium', 'Osmium'),
                  ('iridium', 'Iridium'),
                  ('platinum', 'Platinum'),
                  ('gold', 'Gold'),
                  ('mercury', 'Mercury'),
                  ('thallium', 'Thallium'),
                  ('lead', 'Lead'),
                  ('bismuth', 'Bismuth'),
                  ('polonium', 'Polonium'),
                  ('astatine', 'Astatine'),
                  ('radon', 'Radon'),
                  ('francium', 'Francium'),
                  ('radium', 'Radium'),
                  ('rutherfordium', 'Rutherfordium'),
                  ('dubnium', 'Dubnium'),
                  ('seaborgium', 'Seaborgium'),
                  ('bohrium', 'Bohrium'),
                  ('hassium', 'Hassium'),
                  ('meitnerium', 'Meitnerium'),
                  ('damstadtium', 'Darmstadtium'),
                  ('roentgenium', 'Roentgenium'),
                  ('copernicium', 'Copernicium'),
                  ('nihonium', 'Nihonium'),
                  ('flerovium', 'Flerovium'),
                  ('moscovium', 'Moscovium'),
                  ('livermorium', 'Livermorium'),
                  ('tennessine', 'Tennessine'),
                  ('oganesson', 'Oganesson'),
                  ('lanthanum', 'Lanthanum'),
                  ('cerium', 'Cerium'),
                  ('praseodymium', 'Praseodymium'),
                  ('neodymium', 'Neodymium'),
                  ('promethium', 'Promethium'),
                  ('samarium', 'Samarium'),
                  ('europium', 'Europium'),
                  ('gadolinium', 'Gadolinium'),
                  ('terbium', 'Terbium'),
                  ('dysprosium', 'Dysprosium'),
                  ('holmium', 'Holmium'),
                  ('erbium', 'Erbium'),
                  ('thulium', 'Thulium'),
                  ('ytterbium', 'Ytterbium'),
                  ('lutetium', 'Lutetium'),
                  ('actinium', 'Actinium'),
                  ('thorium', 'Thorium'),
                  ('protactinium', 'Protactinium'),
                  ('uranium', 'Uranium'),
                  ('neptunium', 'Neptunium'),
                  ('plutonium', 'Plutonium'),
                  ('americium', 'Americium'),
                  ('curium', 'Curium'),
                  ('berkelium', 'Barkelium'),
                  ('californium', 'Californium'),
                  ('einsteinium', 'Einsteinium'),
                  ('fermium', 'Fermium'),
                  ('mendelevium', 'Mendelevium'),
                  ('nobelium', 'Nobelium'),
                  ('lawrencium', 'Lawrencium'),
                  ('&#176;', 'Degree sign'),
                  ('&#8710;', 'Increment'),
                  ('mol', 'Mol'),
                  ('bond', 'Bond'),
                  ('doubleBond', 'Double bond'),
                  ('tripleBond', 'Triple bond'),
                  ('chemistryRightArrow', 'Forward reaction'),
                  ('chemistryRightArrowWithOverScript', 'Forward reaction with over script'),
                  ('chemistryRightArrowWithUnderScript', 'Forward reaction with under script'),
                  ('chemistryRightHarpoonOverLeftHarpoon', 'Equilibrium'),
                  ('chemistryRightHarpoonOverLeftHarpoonWithOverScript', 'Equilibrium with over script'),
                  ('chemistryRightHarpoonOverLeftHarpoonWithUnderScript', 'Equilibrium with under script'),
                  ('chemistryRightArrowOverLeftArrow', 'Reaction in both directions'),
                  ('chemistryRightArrowOverLeftArrowWithOverScript', 'Reaction in both directions with over script'),
                  ('chemistryRightArrowOverLeftArrowWithUnderScript', 'Reaction in both directions with under script'),
                  ('chemistryRightArrowWithUnderAndOverScript', 'Forward reaction with under and over script'),
                  ('chemistryRightHarpoonOverLeftHarpoonWithUnderAndOverScript', 'Equilibrium with under and over script'),
                  ('chemistryRightArrowOverLeftArrowWithUnderAndOverScript', 'Reaction in both directions with under and over script'),
                  ('subsuperscript', 'Superscript and subscript'),
                  ('leftSubscriptAndSuperscript', 'Left subscript and superscript'),
                  ('superscript', 'Superscript'),
                  ('subscript', 'Subscript'),
                  ('chemistryParenthesis', 'Parentheses'),
                  ('chemistrySquareBracket', 'Square brackets'),
                  ('chemistryCurlyBracket', 'Curly brackets'),
                  ('copy', 'Press Ctrl+C to copy the selection'),
                  ('cut', 'Press Ctrl+X to cut the selection'),
                  ('paste', 'Press Ctrl+V to paste the content of the clipboard'),
                  ('undo', 'Undo'),
                  ('redo', 'Redo'),
                  ('bold', 'Bold'),
                  ('italic', 'Italic'),
                  ('autoItalic', 'Automatic italic'),
                  ('setColor', 'Color'),
                  ('setUnicode', 'Insert special characters'),
                  ('mtext', 'Regular text'),
                  ('rtl', 'Right to left editing'),
                  ('forceLigature', 'Arabic ligature'),
                  )
              ),
             ('PARCC', 'PARCC','PARCC',
              (
                  ('dollar', 'Dollar sign'),
                  ('questionMark', 'Unknown number'),
                  ('mixedNumber', 'Mixed number'),
                  ('cubeRoot', 'Cube root'),
                  ('exponential', 'Exponential'),
                  ('openInterval', 'Open interval'),
                  ('closedInterval', 'Closed interval'),
                  ('openClosedInterval', 'Open-closed interval'),
                  ('closedOpenInterval', 'Closed-open interval'),
                  ('inverseSecant', 'Arcsecant'),
                  ('inverseCosecant', 'Arccosecant'),
                  ('inverseCotangent', 'Arccotangent'),
                  ('meanOfX', 'Mean of x'),
                  ('meanOfY', 'Mean of y'),
                  ('!', 'Factorial'),
                  ('parccImaginaryI', 'Imaginary number i'),
                  ('negativeSign', 'Negative sign'),
                  ('notCongruent', 'Not approximately equal to'),
                  ('exponentialE', 'Exponential e'),
                  ('deleteAll', 'Clear all'),
                  ('%', 'Percent sign'),
                  )
              ),
             ('general', 'contextual', _("Konteksti vahekaart"),
              (
                  ('nudgeUp', 'Nudge up'),
                  ('nudgeLeft', 'Nudge left'),
                  ('nudgeRight', 'Nudge right'),
                  ('nudgeDown', 'Nudge down'),
                  ('joinNumbersAndSeparators', 'Merge/unmerge separators in'),
                  ('setOpenBracket', 'setOpenBracket'),
                  ('setCloseBracket', 'setCloseBracket'),
                  ('setSeparator', 'setSeparator'),
                  ('fenceVerticalAlignBaseline', 'Baseline'),
                  ('fenceVerticalAlignMiddleBaseline', 'Middle-baseline'),
                  ('fenceVerticalAlignMiddle', 'Middle'),
                  ('stretchy', 'Stretchy'),
                  ('alignLeft', 'Align left'),
                  ('alignCenter', 'Align center'),
                  ('alignRight', 'Align right'),
                  ('alignRelation', 'Relation align'),
                  ('appendRow', 'Insert row below'),
                  ('prependRow', 'Insert row above'),
                  ('appendColumn', 'Insert column at right'),
                  ('prependColumn', 'Insert column at left'),
                  ('removeRow', 'Remove row'),
                  ('removeColumn', 'Remove column'),
                  ('addFrame', 'Insert frame'),
                  ('removeFrame', 'Remove frame'),
                  ('matrixSolidLine', 'Activate solid lines'),
                  ('addLineBelow', 'Insert line below'),
                  ('addLineRight', 'Insert right line'),
                  ('matrixDashLine', 'Activate dash lines'),
                  ('removeLineBelow', 'Remove line below'),
                  ('removeLineRight', 'Remove right line'),
                  ('alignLeft', 'Align left'),
                  ('alignRowsTop', 'Align rows to top'),
                  ('alignRowsBaseline', 'Align rows to baseline'),
                  ('alignCenter', 'Align center'),
                  ('alignRowsCenter', 'Align rows to center'),
                  ('alignRowsAxis', 'Align rows to axis'),
                  ('alignRight', 'Align right'),
                  ('alignRowsBottom', 'Align rows to bottom'),
                  ('alignDecimal', 'Decimal align'),
                  ('alignRelation', 'Relation align'),
                  ('setDecimalAlignSymbol', 'Decimal align symbol'),
                  ('equalRowHeight', 'Force equal row heights'),
                  ('equalColWidth', 'Force equal column widths'),
                  ('setColumnSpacing', 'Column spacing at right'),
                  ('setRowSpacing', 'Row spacing below'),
                  ('stackline', 'Insert line'),
                  ('upDiagonalStrike', 'Up diagonal strike'),
                  ('ligate', 'Join the selected digits in a single column'),
                  ('prependStackRow', 'Prepend row'),
                  ('appendStackRow', 'Append row'),
                  ('carryLocationNW', 'Set carries location at north-west'),
                  ('carryLocationN', 'Set carries location at north'),
                  ('carryLocationNE', 'Set carries location at north-east'),
                  ('carryLocationW', 'Set carries location at west'),
                  ('carries', 'Insert carries in this row'),
                  ('carryLocationE', 'Set carries location at east'),
                  ('carryLocationSW', 'Set carries location at south-west'),
                  ('carryLocationS', 'Set carries location at south'),
                  ('carryLocationSE', 'Set carries location at south-east'),
                  ('stackIndentLeft', 'Move to left'),
                  ('stackIndentRight', 'Move to right'),
                  ('setStackCharSpacing', 'Spacing between digits'),
                  )
              ),
             (None, 'advanced', _("Nupud edasijõudnutele"),
              (
                  ('setDisplay', 'Toggle equation inline/block'),
                  ('setDisplayBlock', 'Display as block'),
                  ('setDisplayInline', 'Display as inline'),
                  ('invisiblePlus', 'Invisible plus'),
                  ('invisibleTimes', 'Invisible times'),
                  ('invisibleSeparator', 'Invisible separator'),
                  ('invisibleFunctionApplication', 'Invisible function application'),
                  ('autoDigitSeparatorsMode', 'Merge separators into'),
                  ('setDefaultDecimalSeparator', 'Separators'),
                  )
              )
             )
             
        return iconsets
