--GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO eisikud;
--GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO eisikud;
--GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO eisikud;
--GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA public TO eisikud;
--GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public TO eisikud;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO eisikud;
GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO eisikud;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO eisikud;
